### PR TITLE
chore: remove duplicate import

### LINKED ISSUE #1531: '../../../../../' import is duplicated.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYi11WWRv00OrnWaYQoq&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYi11WWRv00OrnWaYQoq&tab=code

### LINKED ISSUE #1534: '../../helpers' import is duplicated.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYXfK942-0g9lMaA1TxE&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYXfK942-0g9lMaA1TxE&tab=code

### PR DESCRIPTION
**Pull request by princerajpoot20**
**Related issue(s)**

Resolves #1531 and resolve warning: Prefer using nullish coalescing operator.
Resolves #1534

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
@princerajpoot20 looks like you got some linting issues :) 

https://github.com/asyncapi/modelina/actions/runs/6394998663/job/17357653858?pr=1542

**Comment by princerajpoot20** [comment]
@jonaslagoni All set now :)

**Review by jonaslagoni — APPROVED** [review]
👍

**Pull request merged**
