### PR TITLE
docs: make notice about next branch

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR makes notice about the next branch so going forward any features should be targeting it.

### CODE REVIEW

**Review by Samridhi-98 — APPROVED** [review]

**Review by magicmatatjahu — APPROVED** [review]
@jonaslagoni bot didn't merge it.

**Comment by jonaslagoni** [comment]
cc @derberg

**Comment by derberg** [comment]
well, it was 19 days ago, no issues anywhere since then, so I just assume it was random 🤷🏼

**Comment by derberg** [comment]
example that all is good elsewhere https://github.com/asyncapi/spec/pull/833

**Comment by derberg** [comment]
we can, of course, think about extending the orphan-monitor workflow that we already have for PRs from bots. Wdyt?

**Pull request merged**
