### PR TITLE
docs: add example to use custom enum value name

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This example is to showcase and answer https://stackoverflow.com/questions/72530361/asyncapi-enum-with-specific-values

### CODE REVIEW

**Review by magicmatatjahu — DISMISSED** [review]
LGTM! However, we I think that we should change `chore` to the `docs`, even if you added new example.

**Comment by jonaslagoni** [comment]
> LGTM! However, we I think that we should change `chore` to the `docs`, even if you added new example.

True, changing :)

**Comment by magicmatatjahu** [comment]
@jonaslagoni Yeah, I see that also on other PRs, but as I see they try to fix it https://github.com/actions/setup-node/issues/516

**Comment by jonaslagoni** [comment]
@magicmatatjahu lets just wait for the fix then, no rush and I dont want to start changing the CI back and furth.

**Comment by magicmatatjahu** [comment]
@jonaslagoni You can merge it :)

**Review by magicmatatjahu — APPROVED** [review]

**Pull request merged**
