### PR TITLE
fix: added loading animation

### LINKED ISSUE #1725: Add loading animation for when playground generate models
#### Reason/Context

https://modelina.org/playground

When you change the input, open the playground, or change the settings, the playground need to ask the backend to re-generate the models, and there can be a significant delay here depending on input and latency to the backend server. Therefore I suggest we add a loading screen to the output models view that showcases that it is currently in the process of being generated.

You can find the most relevant code for the playground here: https://github.com/asyncapi/modelina/blob/master/modelina-website/src/components/playground/Playground.tsx

And the output panel can be found here: https://github.com/asyncapi/modelina/blob/master/modelina-website/src/components/playground/OutputNavigation.tsx

### PR DESCRIPTION
**Pull request by utnim2**
## Description
Added loading animation

## Related Issue
Fixes #1725 

## Checklist
- [✅] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by Min2who** [comment]
@jonaslagoni should i add a animated loading icon ? or this is fine

**Comment by devilkiller-ag** [comment]
Hi @Min2who, I can see the loading screen on both the input and output panel (I think this should only be on the output panel cc: @jonaslagoni) only when the website is loaded for the first time, but not when we change any setting. We also want the loading screen (on the output panel only) when we tweak settings.

**Review by devilkiller-ag — CHANGES_REQUESTED** [review]
Hi @Min2who, I can see the loading screen on both the input and output panel (I think this should only be on the output panel cc: @jonaslagoni) only when the website is loaded for the first time, but not when we change any setting. We also want the loading screen (on the output panel only) when we tweak settings.

**Comment by Min2who** [comment]
> Hi @Min2who, I can see the loading screen on both the input and output panel (I think this should only be on the output panel cc: @jonaslagoni) only when the website is loaded for the first time, but not when we change any setting. We also want the loading screen (on the output panel only) when we tweak settings.

@devilkiller-ag can yu check it one more time the loading screen is only in the output screen only

**Comment by devilkiller-ag** [comment]
> > Hi @Min2who, I can see the loading screen on both the input and output panel (I think this should only be on the output panel cc: @jonaslagoni) only when the website is loaded for the first time, but not when we change any setting. We also want the loading screen (on the output panel only) when we tweak settings.
> 
> @devilkiller-ag can yu check it one more time the loading screen is only in the output screen only

Here is the screenshot of my inspection. It's showing loading screen on both input editor panel and output panel.
Screenshot (325)

**Comment by Min2who** [comment]
> > > Hi @Min2who, I can see the loading screen on both the input and output panel (I think this should only be on the output panel cc: @jonaslagoni) only when the website is loaded for the first time, but not when we change any setting. We also want the loading screen (on the output panel only) when we tweak settings.
> > 
> > 
> > @devilkiller-ag can yu check it one more time the loading screen is only in the output screen only
> 
> Here is the screenshot of my inspection. It's showing loading screen on both input editor panel and output panel. Screenshot (325)

@devilkiller-ag this is not because of my changes that i have made
This loading is present in the website only

**Comment by jonaslagoni** [comment]
Any updates here? 👀

**Comment by Min2who** [comment]
> Any updates here? 👀

@jonaslagoni can you review the pr .I have added the loading animation on the output screen

**Comment by jonaslagoni** [comment]
@Min2who all you @devilkiller-ag

**Comment by devilkiller-ag** [comment]
Hi @Min2who @jonaslagoni, I will review the PR tomorrow as I don't have my laptop with me for now.
@Min2who Can you tick all the checklists in the PR description for then?

**Comment by devilkiller-ag** [comment]
Any updates on this @Min2who?

**Comment by Min2who** [comment]
> Any updates on this @Min2who?


https://github.com/asyncapi/modelina/assets/127925465/2f726f40-5ae7-4a2d-8519-18162eedffcf

**Comment by devilkiller-ag** [comment]
@Min2who That looks good to me. But don't you think we should also screen-load animation while changing the options 🤔? 

https://github.com/asyncapi/modelina/assets/43639341/affa5e64-f25d-45ea-bc0a-9db19327709e

@jonaslagoni What do you think?

**Comment by jonaslagoni** [comment]
I agree @devilkiller-ag, its actually part of the issue description ✌️
>When you change the input, open the playground, or change the settings, ...

**Comment by Min2who** [comment]
> @Min2who That looks good to me. But don't you think we should also screen-load animation while changing the options 🤔?
> 
>  2024-02-02.07-54-59.mp4 
> @jonaslagoni What do you think?

doing it 🙇‍♂️

**Comment by jonaslagoni** [comment]
Hey @Min2who have you had a chance to take a look at it? :v:

**Comment by devilkiller-ag** [comment]
@jonaslagoni should I close this PR as we have not got any updates from @utnim2 since last two months?

**Comment by utnim2** [comment]
I am really sorry for it @jonaslagoni @devilkiller-ag

**Pull request closed without merging**
