### PR TITLE
fix: typescript unions not being serialized if referenced model

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR fixes a bug where a union, array of union, and arrays is not correctly serialized i.e. the `marshal` function of a referenced class is not called, and the instance is instead serialized without respecting the underlying `unconstrainedPropertyName`.

There is also a problem with the unmarshalling... Because at the moment the classes are not correctly created, but I will have to fix that later 🙃

### CODE REVIEW

**Review by kennethaasan — DISMISSED** [review]

**Comment by jonaslagoni** [comment]
Just realized that I am not taking multiple types into account such as arrays with unions, regular arrays, regular unions, etc... Gonna add some more 😓

**Comment by jonaslagoni** [comment]
The sonarcloud reporting has nothing to do with the changes introduced here. Dont know why it all of the sudden reports those 🤨

**Review by Samridhi-98 — APPROVED** [review]
LGTM 🎉

**Comment by jonaslagoni** [comment]
Thanks @Samridhi-98 🙇 

/rtm

**Pull request merged**
