### PR TITLE
chore: resolves warnings

### LINKED ISSUE #1512: Remove this unused import of 'DefaultEnumKeyConstraints'.
Unnecessary imports should be removed.

more info here https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvXHXBcnZgI4LLXP

### LINKED ISSUE #1513: Prefer using an optional chain expression instead, as it's more concise and easier to read.
more about this issue here https://sonarcloud.io/project/issues?open=AYjaFvXHXBcnZgI4LLXQ&id=asyncapi_generator-model-sdk

### LINKED ISSUE #1515: '../../src' import is duplicated.
More info can be found here https://sonarcloud.io/project/issues?open=AYjaFvhIXBcnZgI4LLXZ&id=asyncapi_generator-model-sdk

### LINKED ISSUE #1516: '../../src' import is duplicated.
Duplicated import found in `examples/javascript-generate-marshalling/index.ts`. More info here https://sonarcloud.io/project/issues?open=AYjaFvMDXBcnZgI4LLXN&id=asyncapi_generator-model-sdk

Having the same module imported multiple times can affect code readability and maintainability. It makes hard to identify which modules are being used.

Instead, one should consolidate the imports from the same module into a single statement. By consolidating all imports from the same module in a single import statement, the code becomes more concise and easier to read, as there is only one import statement to keep track of. Additionally, it can make it easier to identify which modules are used in the code.

`import { B1, B2 } from 'b';`

### LINKED ISSUE #1517: Remove this unused import of 'pascalCase'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXS&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXS

### LINKED ISSUE #1518: Remove this unused import of 'CommonModel'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXT&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXT&tab=code

### LINKED ISSUE #1519: Remove this unused import of 'InterpreterSchemaType'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXU&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXU&tab=code

### LINKED ISSUE #1520: Remove this unused import of 'Interpreter'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXV&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXV&tab=code

### LINKED ISSUE #1521: Remove this unused import of 'InterpreterOptions'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXW&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXW&tab=code

### LINKED ISSUE #1522: Remove this unused import of 'isModelObject'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXX&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvZzXBcnZgI4LLXX&tab=code

### LINKED ISSUE #1523: Remove this unused import of 'OpenAPIV2'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvYNXBcnZgI4LLXR&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFvYNXBcnZgI4LLXR&tab=code

### LINKED ISSUE #1524: Prefer using an optional chain expression instead, as it's more concise and easier to read.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYfetcF1Z7vWCKmmWMYy&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYfetcF1Z7vWCKmmWMYy&tab=code

### LINKED ISSUE #1525: Remove duplicates in this character class.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH5_6xKyPQbw46W-Z&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH5_6xKyPQbw46W-Z&tab=code

### LINKED ISSUE #1527: Remove this property or method or refactor "DartGeneratorOptions", as "context" is not used inside component body
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH59FxKyPQbw46W-H&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH59FxKyPQbw46W-H&tab=code

### LINKED ISSUE #1535: Remove this unused import of 'KOTLIN_DEFAULT_PRESET'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFwr-XBcnZgI4LLXt&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFwr-XBcnZgI4LLXt&tab=code

### LINKED ISSUE #1536: Remove this unused import of 'JAVA_COMMON_PRESET'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFwr-XBcnZgI4LLXu&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFwr-XBcnZgI4LLXu&tab=code

### PR DESCRIPTION
**Pull request by princerajpoot20**
**Description**

- Resolves Warnings

**Related issue(s)**

1. Resolves #1512 
2. Resolves #1513 
3. Resloves #1514 
4. Resolves #1515 
5. Resolves #1516 
6. Resolves #1517 
7. Resolves #1518  
8. Resolves #1519  
9. Resolves #1520  
10. Resolves #1521 
11. Resolves #1522
12. Resolves #1523
13. Resolves #1524
14. Resolves #1525 
15. Resolves #1527 
16. Resolves #1535 
17. Resolves #1536

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Got some linting errors 🙂

**Comment by princerajpoot20** [comment]
@jonaslagoni Done, sorry for that 🙂

**Review by jonaslagoni — APPROVED** [review]
Nice 👍

**Pull request merged**
