### PR TITLE
fix: make parameter type of ToEnum extension methods dynamic

### PR DESCRIPTION
**Pull request by jespitae**
## Description
Changed parameter type of ToEnum extension methods to dynamic.

## Related Issue
fixes https://github.com/asyncapi/modelina/issues/2063

## Checklist
- [ ] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Make sure to update test `npm run test:update` 🙂

**Comment by jespitae** [comment]
> Make sure to update test `npm run test:update` 🙂

Hi @jonaslagoni,

Running npm run test:update results in all the snapshots being updated, which seems incorrect:
image
For example:
image
I guess there is something wrong with my development setup?

**Comment by jonaslagoni** [comment]
> > Make sure to update test `npm run test:update` 🙂
> 
> Hi @jonaslagoni,
> 
> Running npm run test:update results in all the snapshots being updated, which seems incorrect: image For example: image I guess there is something wrong with my development setup?

I have seen this before, but I cant remember what did it. Think I cleared cache and installed dependencies again 🤔

**Comment by jonaslagoni** [comment]
What node version are you using? 🤔

**Comment by jespitae** [comment]
> What node version are you using? 🤔

image

**Comment by jonaslagoni** [comment]
@jespitae try downgrade to v18 and clear cache, that is what I am currently using.

**Comment by jespitae** [comment]
> @jespitae try downgrade to v18 and clear cache, that is what I am currently using.

Hey,

I tried downgrading to v18. Same result still.
image

**Comment by jonaslagoni** [comment]
@jespitae i am gonna try pull your changes and see if i get the same problem. Will do it later tonight ✌️

**Comment by jonaslagoni** [comment]
Finally had some time to sit down and try and reproduce it.

What system are you using @jespitae? Windows?

**Comment by jonaslagoni** [comment]
Looks like I have found a "bug" in the core of the Modelina models... How the hell that bug has not explicitly shown up before puzzles me... It looks like a small discrepancy between windows and linux/mac node/typescript/npm something that makes it show up there 🤨

**Comment by jespitae** [comment]
> Finally had some time to sit down and try and reproduce it.
> 
> What system are you using @jespitae? Windows? That is where I can reproduce it.

Indeed it's on windows.

**Comment by jonaslagoni** [comment]
@jespitae can you try update your branch with the latest next branch?

**Comment by jonaslagoni** [comment]
@jespitae I am gonna quickly fix it and merge it in another branch. Thanks for taking the time and sorry for the long time it took.

**Comment by jonaslagoni** [comment]
@all-contributors please add @jespitae for code, bug

**Pull request merged**
