### PR TITLE
chore(website): improve the example display name

### LINKED ISSUE #1417: Improve the example display name
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  To improve the UI of the examples page
- How will this change help?
  It will improve the UI

#### Description
Please try answering few of those questions
- What changes have to be introduced?
 A small changes of docs 
- Will this be a breaking change?
  No

image

In this we can remove dash and make the first letter capital

image

### PR DESCRIPTION
**Pull request by aryanas159**
**Description**
Improved the example display names on the examples page by making a function to modify the string.

**Related issue(s)**

Screenshot 2023-07-07 200215
Screenshot 2023-07-07 201545

Resolves #1417

### CODE REVIEW

**Review by sambhavgupta0705 — APPROVED** [review]
LGTM 🚀

**Comment by sambhavgupta0705** [comment]
@aryanas159 let @jonaslagoni come back then we will merge it

**Review by jonaslagoni — APPROVED** [review]
Perfect, thanks @aryanas159 💪

**Review by jonaslagoni — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@all-contributors please add @aryanas159 for code

**Pull request merged**
