### PR TITLE
chore(website): add responsive sidebar to examples

### LINKED ISSUE #1315: Make sidebar responsive and collapsible
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
To make the site readable in mobile view,

Screenshot from 2023-05-24 11-14-05

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Add responsiveness to the sidebar by making it collapsable

### PR DESCRIPTION
**Pull request by Bhavik-ag**
**Description**
- Made sidebar responsive for the mobile view by making it collapsable

**Related issue(s)**
fixes #1315

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
Hey @Bhavik-ag 
It would be nice if we align the heading and description to a little left with `see example on github button`
image

**Comment by sambhavgupta0705** [comment]
image
this button also

**Comment by Bhavik-ag** [comment]
@sambhavgupta0705 Thanks for pointing out these alignment issues. I've made the necessary changes.

**Comment by sambhavgupta0705** [comment]
Welcome @Bhavik-ag 

one more point that it would be good in terms of UI if we align the whole page a little left (in the same axes that of modelina logo or a little more left)
image
@jonaslagoni what's your opinion on this

**Comment by jonaslagoni** [comment]
Unless its something specific to the changes proposed here, then it goes into another PR/issue 🙂 

> one more point that it would be good in terms of UI if we align the whole page a little left (in the same axes that of modelina logo or a little more left)

I don't see it as an issue 😄 But I am no designer either 😆 

So yea, this change seem to be rather hard to pull off since the two layouts are completely separated, so I would create an issue for it.

**Comment by jonaslagoni** [comment]
@all-contributors please add @Bhavik-ag for design

**Pull request merged**
