### PR TITLE
chore: add ferror to PHP codeowners

### PR DESCRIPTION
**Pull request by Ferror**
Let's try to maintain and expand PHP generator 😄

### CODE REVIEW

**Review by jonaslagoni — APPROVED** [review]
Welcome onboard, glad to have you 💪 Let me know if you need some help with figuring out the future for PHP 👍 

You should have received the invite to join as a maintainer. Remember you can ask to be added to the AsyncAPI TSC, see `step 5`: https://github.com/asyncapi/community/blob/master/Become-maintainer-in-existing-project.md

Pinging existing code owners, the family grows 🎉  @magicmatatjahu @kennethaasan @leigh-johnson @Samridhi-98 @ron-debajyoti

**Comment by jonaslagoni** [comment]
@Ferror just pinging you to make sure you know that you are free to join the AsyncAPI TSC now that you are codeowner of Modelina 🙂

**Comment by Ferror** [comment]
> @Ferror just pinging you to make sure you know that you are free to join the AsyncAPI TSC now that you are codeowner of Modelina 🙂

Now i know... 😄

**Comment by jonaslagoni** [comment]
As a TSC member you dont have to vote if you ain't got the time, but it merely shows you are a codeowner in one of the tools 🙂 Also it can be a place for your company to promote open source cc @derberg

**Pull request merged**
