### PR TITLE
feat!: add discriminator support for OpenAPI v3 and Swagger v2

### PR DESCRIPTION
**Pull request by dlkj**
**Description**

- Add `discriminator` support for `OpenAPI` and `Swagger` schema

**Related issue(s)**
Follows on from #1271, #1270, #1269 and  #1169

### CODE REVIEW

**Review by jonaslagoni — COMMENTED** [review]
You have some linting issues 🙂

**Comment by jonaslagoni** [comment]
You can ignore the black box tests, those are fixed in https://github.com/asyncapi/modelina/pull/1283

**Review by jonaslagoni — COMMENTED** [review]
Otherwise, it looks good to me 👍 

@kennethaasan wanna have a look?

**Comment by dlkj** [comment]
Will address the linter problems. Expect a push later today.

**Comment by kennethaasan** [comment]
LGTM as well 👍

**Review by jonaslagoni — APPROVED** [review]

**Pull request merged**
