### PR TITLE
fix: deprecated Website Shop Link in Footer

### PR DESCRIPTION
**Pull request by devansh-m12**
## Description
This pull request addresses the issue of a deprecated website shop link in the footer section of the site. The current link is pointing to an outdated URL, leading to a irrelevant page. This PR updates the link to ensure users are directed to the correct and up-to-date shop page.

## Related Issue
[[website bug]: update the link to async api Shop in the footer section of website](https://github.com/asyncapi/modelina/issues/1666)](https://github.com/asyncapi/modelina/issues/1666)

## Changes Made
- Updated the website shop link in the footer to the new, correct URL.
- Ensured that the link now points to the relevant and active shop page.

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
Hey @ devansh-m12, @ anchalpanwar17 was already working on it. @anchalpanwar17 Have you started working on this issue (#1666)? If not would you like to transfer it to @devansh-m12? @devansh-m12 I would suggest you inform us that you would like to work on an issue before starting work on it.

**Comment by devansh-m12** [comment]
@devilkiller-ag ohh my bad, I'll make sure to remember that.

**Comment by jonaslagoni** [comment]
@devilkiller-ag as there has been no specific response from the other two, and this PR is already up, I would vote to just merge/review this one 🙂 

What matters is creating the PR, not so much saying you want to do it. However, @devansh-m12 it is good practice to let others have some days when they say they wanted to complete it before doing the issue yourself 😄 Just so no one is wasting time is the most important one 👍

**Comment by devilkiller-ag** [comment]
Hi @devansh-m12 @jonaslagoni, This issue was previously solved by the PR #1705

**Comment by devilkiller-ag** [comment]
Fixed #1666

**Pull request closed without merging**
