### PR TITLE
chore: add new example for json-schema-draft4-from-object (#852)

### LINKED ISSUE #852: Add a new example for JSON Schema draft 4
#### Reason/Context
Currently, we only have an [example for JSON Schema draft 7](https://github.com/asyncapi/modelina/tree/master/examples/json-schema-draft7-from-object), I think it would make sense to add another one for draft 4. 

**Remember to create your branch from the `next` branch and NOT `master` and also target the PR towards `next`.**

#### Description
You can copy the draft 7 example folder, and rename it to `json-schema-draft4-from-object` and then apply the following changes:
- Change the[ draft 7 schema to draft 4](https://github.com/asyncapi/modelina/blob/6c9c7039068e63f609e4b666fb8615998ac525d7/examples/json-schema-draft7-from-object/index.ts#L4):
```
const jsonSchemaDraft4 = {
  $schema: 'http://json-schema.org/draft-04/schema#',
  type: 'object',
  additionalProperties: false,
  properties: {
    email: {
      type: 'string',
      format: 'email'
    }
  }
};
```
- Adapt the package file: https://github.com/asyncapi/modelina/blob/25203c71bd55d6d8e84a8c9aa4672e5d3e857504/examples/json-schema-draft7-from-object/package.json#L2 with the new folder name
- Adapt the readme file https://github.com/asyncapi/modelina/blob/next/examples/json-schema-draft7-from-object/README.md
- Update the test snapshots `npm run test:examples -- -u`
- Add your example to the list of examples https://github.com/asyncapi/modelina/blob/next/examples/README.md
- Add your example to the usage docs: https://github.com/asyncapi/modelina/blob/next/docs/usage.md#generate-models-from-json-schema-documents. Do this by adding a new list item called `Generate from a JSON Schema draft 4 pure JS object`

Feel free to reach out if you have any questions 🙂

### PR DESCRIPTION
**Pull request by nitintejuja**
**Description**
- Added new example for json-schema-draft4-from-object as mentioned in #852 

**Related issue(s)**
Fixes #852

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
@nitintejuja thanks for taking the time to provide this!

I think you need to remove the snapshot file and re-run the test, as this is what fails the snapshots. `npm run test -- -u` currently does not work.

**Comment by nitintejuja** [comment]
@jonaslagoni i have modified snapshots. can you check once?

**Comment by nitintejuja** [comment]
sure @jonaslagoni

**Review by Samridhi-98 — APPROVED** [review]
LGTM 👍🏻

**Comment by jonaslagoni** [comment]
I am gonna fix the CI problem later, lets merge it 👍

**Review by jonaslagoni — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@all-contributors please add @nitintejuja for example

**Comment by nitintejuja** [comment]
@jonaslagoni and @Samridhi-98 thanks for guiding me. this project is very interesting to me.

**Pull request merged**
