### PR TITLE
fix: added scala to playground

### LINKED ISSUE #1690: Add Scala generator to playground
#### Reason/Context
With the new Scala generator, we need to add it to the playground so people can play around with it. It should be fairly straightforward;

TODO;
- Add the generator API function: https://github.com/asyncapi/modelina/tree/master/modelina-website/src/pages/api/functions
- Integrate it into the main generate function; https://github.com/asyncapi/modelina/blob/master/modelina-website/src/pages/api/generate.ts
- Adapt the playground to call the new generator code (use the existing generator code as guideline): https://github.com/asyncapi/modelina/tree/master/modelina-website/src/components/playground

### PR DESCRIPTION
**Pull request by Min2who**
## Description
added scala to playground

## Related Issue
Fixes #1690 

## Checklist
- [ ✅] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
Hi @Min2who, any update on this?

**Comment by Min2who** [comment]
@devilkiller-ag @jonaslagoni can yu review the pr if i am going in the right direction

**Review by devilkiller-ag — COMMENTED** [review]
Seems good from my side, you can continue to work ahead. Make sure that all checks are passed.

**Comment by jonaslagoni** [comment]
Any update @Min2who otherwise I will open it up to others to solve this 🙂

**Comment by Min2who** [comment]
> Any update @Min2who otherwise I will open it up to others to solve this 🙂

can i take a day or two @jonaslagoni

**Comment by jonaslagoni** [comment]
@Min2who as long as you are working on it and not hogging the task while doing multiple tasks at the same time, then you are fine 👍

**Comment by jonaslagoni** [comment]
Any update here @Min2who?

**Comment by Min2who** [comment]
i am not working on it . Let @AkhilJ321 try this !

**Pull request closed without merging**
