### PR TITLE
feat: add dart generator.

### PR DESCRIPTION
**Pull request by rmasarovic**
**Description**

- add dart generator for class and enums
- add json serializer(create annotion for class ,helpers methods, imports for library json_serializable )

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Awesome @rmasarovic 🎉 

The only thing missing is tests and docs!

- We need to add a Dart specific documentation for the JSON preset you added: https://github.com/asyncapi/modelina/tree/master/docs/languages
- We need to add an example for the Dart JSON preset, read more about how to add it here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-examples
- We need to add the basic usage example for Dart to the docs: https://github.com/asyncapi/modelina/blob/master/docs/usage.md
- We need to add Dart to the main readme: https://github.com/asyncapi/modelina#features

Furthermore, we need to add tests to cover at least the current test coverage (93%).

Feel free to ping me if you get stuck!

**Comment by rmasarovic** [comment]
@jonaslagoni  hi i try to add documentation and tests maybe now it will be good

**Review by jonaslagoni — APPROVED** [review]
> @jonaslagoni hi i try to add documentation and tests maybe now it will be good

This is so awesome! 

I have absolutely no comments for it 🔥 

Only a final remark, would you like [to champion and maintain the Dart generator](https://github.com/asyncapi/modelina/blob/master/CODEOWNERS) or are you only interested in contributing it? 🙂 Feel free to ping me on slack when you have considered it 🙇

**Comment by jonaslagoni** [comment]
@all-contributors please add @rmasarovic for code, docs, test, example

**Pull request merged**
