### PR TITLE
docs: updated footer with heart emoji

### PR DESCRIPTION
**Pull request by officialasishkumar**
## Related Issue
[1726](https://github.com/asyncapi/modelina/issues/1726)

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by AnimeshKumar923** [comment]
referencing a issue in which this change was discussed: https://github.com/asyncapi/website/issues/1535

cc: @jonaslagoni @devilkiller-ag

**Review by devilkiller-ag — APPROVED** [review]

**Comment by devilkiller-ag** [comment]
Thanks @officialasishkumar 🔥 Feel Free to solve more issues here ✨

**Comment by jonaslagoni** [comment]
@all-contributors please add @officialasishkumar for docs

**Pull request merged**
