### PR TITLE
fix: add serialization alias for Pydantic 

### PR DESCRIPTION
**Pull request by jonaslagoni**
## Description
This PR adds serialization alias field tags for the Pydantic preset, so properties are accurately serialized and deserialized

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@dimitern another one.

**Comment by jonaslagoni** [comment]
This PR becomes even more important when we switch to the standardized styling format for properties as they are no longer 1:1 representation in most cases.

https://github.com/asyncapi/modelina/pull/1861

**Comment by dimitern** [comment]
Looks good to me

**Comment by jonaslagoni** [comment]
Thanks folks 🙇

**Pull request merged**
