### PR TITLE
chore(website): add basic markdown functionality

### PR DESCRIPTION
**Pull request by Shurtu-gal**
**Description**

 - Currently trying to integrate docs

**Related issue(s)**
#1161

### CODE REVIEW

**Comment by Shurtu-gal** [comment]
@jonaslagoni I have made a very basic markdown rendering functionality.
Can you guide me towards how you want the design to be?
Also I guess we have to add certain things in markdown itself for better descriptions in headers.

**Comment by Shurtu-gal** [comment]
Sure, but it will take some time, I guess. @jonaslagoni.
Meanwhile, do you have some design in your mind regarding the docs page?

**Comment by jonaslagoni** [comment]
I was thinking similar to the examples 🤔

But thats not a hard ask, feel free to make your own impression and decision 🤞😄

**Comment by Shurtu-gal** [comment]
Sure let me see what I can whip up then.

**Comment by jonaslagoni** [comment]
Hey @Shurtu-gal, any update here? How far along are you and do you think you can finish it or need someone else to take over?

**Pull request closed without merging**
