### PR TITLE
chore(website): add typescript map type option to the playground

### LINKED ISSUE #1756: Add typescript `mapType` option to the playground
#### Reason/Context
There is an option for the TypeScript generator that is currently unsupported in the playground called `mapType`.

We need to create add it as an option for the playground.

@devilkiller-ag any chance you want to have a look at this or adapt the issue to good-first-issue so others can pick it up?

### PR DESCRIPTION
**Pull request by devilkiller-ag**
## Description
Add TypeScript option for `mapType` to the playground.

## Related Issue
Fixes #1756 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

## Additional Notes

@jonaslagoni

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
@jonaslagoni I wanted to confirm if the default `mapType` is `indexedOpject` or `map`?

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Just one change :v: 

Yea, default value is `map` type 🙂

**Review by jonaslagoni — APPROVED** [review]
Awesome @devilkiller-ag 🔥

**Comment by devilkiller-ag** [comment]
Thanks @jonaslagoni, I saw at many places in the code that default map type value was set to `indexedObject`.

**Pull request merged**
