### PR TITLE
chore: add resizable property in playground

### LINKED ISSUE #1846: [FEATURE]  Add Stretchable Sidebar to Playground
### Why do we need this improvement?

We need this improvement to enhance the user experience and usability of the Playground section in our project. Currently, users have the option to hide the entire sidebar, but they cannot resize or stretch the sidebar to view the full code content. This limitation can be frustrating for users, especially when they need to view longer sections of code without excessive scrolling.

By adding a stretchable sidebar feature, users would have the flexibility to expand the width of the sidebar horizontally, allowing them to view the entire code content comfortably. This enhancement would improve the overall usability of the Playground section and make it more intuitive and user-friendly.

this improvement is necessary to provide a smoother and more efficient experience for users interacting with the Playground section, ultimately enhancing their ability to navigate and interact with the code effectively.

### How will this change help?

This change will help improve the usability and functionality of the Playground section in our project in several ways:

1. Enhanced Viewing Experience: The addition of a stretchable sidebar will allow users to expand the width of the sidebar horizontally, enabling them to view the entire code content without having to scroll excessively. This will enhance the overall viewing experience and make it easier for users to navigate and understand the code.

2. Increased Efficiency: With the ability to stretch the sidebar, users can quickly access and review longer sections of code without the need for repetitive scrolling. This will save time and effort for users, increasing their efficiency when interacting with the Playground section.

3. Improved Accessibility: The stretchable sidebar feature will make the code content more accessible to users with varying screen sizes and resolutions. Users will be able to adjust the width of the sidebar according to their preferences and viewing devices, ensuring optimal readability and usability for all users.

4. Better Code Analysis: By providing users with a clear and unobstructed view of the entire code content, the stretchable sidebar will facilitate better code analysis and comprehension. Users will be able to focus on understanding the code logic and structure without distractions or limitations imposed by the interface.

this change will significantly enhance the usability, efficiency, and accessibility of the Playground section, ultimately improving the overall user experience and satisfaction with our project.

### Screenshots

image
image

### How could it be implemented/designed?

1. **User Interface Design:**
   - Add a draggable handle or separator between the sidebar and the main content area.
   - When users hover over the handle, display a cursor indicating that the handle is draggable.
   - Implement visual feedback, such as a change in cursor appearance or highlighting, to indicate the dragging action.

2. **Resize Functionality:**
   - Allow users to click and drag the handle horizontally to resize the width of the sidebar.
   - Implement logic to dynamically adjust the width of the sidebar and the content area as the handle is dragged.

3. **Constraints and Limits:**
   - Set minimum and maximum widths for the sidebar to prevent it from becoming too narrow or too wide, ensuring a usable and aesthetically pleasing layout.
   - Consider responsive design principles to accommodate different screen sizes and resolutions.

4. **Persistence:**
   - Save the user's preferred sidebar width in local storage or as part of their user settings, so that it persists across sessions.
   - Ensure that the selected sidebar width is maintained when navigating between pages or refreshing the browser.

5. **Accessibility Considerations:**
   - Ensure that the stretchable sidebar feature is accessible to users with disabilities by providing keyboard navigation options and ensuring compatibility with screen readers.
   - Implement appropriate aria roles and attributes to convey the purpose and state of the stretchable sidebar to assistive technologies.

6. **Testing and Iteration:**
   - Conduct usability testing with a diverse group of users to gather feedback on the implementation and design of the stretchable sidebar feature.
   - Iterate on the design based on user feedback and make necessary adjustments to improve usability and user satisfaction.

the stretchable sidebar feature can be implemented and designed to provide users with a flexible and intuitive way to resize the sidebar according to their preferences, enhancing the overall user experience of the Playground section in our project.

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

### PR DESCRIPTION
**Pull request by AKACHI-4**
**Description**
- used `react-resizable-panels` to implement resizing into the `editor` and `output` components

**File Changed**
- `Content.tsx`

**Related issue(s)**
Fixes #1846 

**Additionals**
Playground _ Modelina

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
Hi @AKACHI-4, There are few things we need to fix:
- Can you please add a bar between the editors indicating that it can be resizeable? Something similar to this:
image

- Collapsing the left (input) editor should not collapse the general options.
- Right editor along with output navigator is not being collapsed fully. Kindly fix this.

**Comment by jonaslagoni** [comment]
@devilkiller-ag do you have time to take a look?

**Comment by devilkiller-ag** [comment]
> @devilkiller-ag do you have time to take a look?

Hi @jonaslagoni, I think I gave my review earlier on this 🤔

**Review by devilkiller-ag — COMMENTED** [review]
Gave my review here: https://github.com/asyncapi/modelina/pull/1908#issuecomment-2019916486

**Comment by AKACHI-4** [comment]
Hey @devilkiller-ag, Surely look but first I have some thoughts

> * Can you please add a bar between the editors indicating that it can be resizable?

yea, sure. should it be more stylish as you suggested ?

> * Collapsing the left (input) editor should not collapse the general options.

yeah, got that. It should apply the same for the right panel as well.

> * Right editor along with output navigator is not being collapsed fully. Kindly fix this.

actually, I intentionally did that because when I completely collapse the right panel, there's no way I'll be able to use the resizable bar again since it will be hidden inside the `overflow-y`.

**Possible fixes :**
- use low-opacity scrollbar for that.
- use `w-5` for the bar, but that might look too wide.

**some observation :** I checked vs-code, and its a fix there too. This means that in the 2-panel view, if we collapse right one, there's no way to get it back.

**Comment by AKACHI-4** [comment]
kindly suggest some more improvement i can perform on pr.

**Review by devilkiller-ag — CHANGES_REQUESTED** [review]
>  should it be more stylish as you suggested ?
Yeah. I think it would be nice if we also add a button with an arrow icon at the center of the bar which can:
- Reset the view.
- The arrow icon should be towards right, when the output editor is taking the majority of view.
- The arrow icon should be towards left, when the input editor is taking the majority of view.

> It should apply the same for the right panel as well.
No, Because the output navigator is the part of output itself. There is no sense to change output files if you can't view them in the extreme case (when the output view is not visible).

**Comment by devilkiller-ag** [comment]
Any update on this @AKACHI-4?

**Comment by AKACHI-4** [comment]
Hey @devilkiller-ag I will PR next week due to exam this week. tho

**Comment by devilkiller-ag** [comment]
Hi @AKACHI-4, did you had a chance to look up on this work?

**Comment by AKACHI-4** [comment]
Yeah @devilkiller-ag I did changes locally, but sort of incomplete what left is the arrow sign which changes direction on majority width. 

Will do a raw commit by this evening.

**Comment by devilkiller-ag** [comment]
Hi @AKACHI-4 any updates on this?

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, I am closing this PR since we have no updates from @AKACHI-4. I will share this issue with the community. If no one grabs it, then if time allows I will work on it.

**Pull request closed without merging**
