### PR TITLE
feat: added loading animation in output 

### PR DESCRIPTION
**Pull request by Alokih**
## Description
Added a loading... message in output, if there is any change in input field or other general options 

## Related Issue
Fixes: #1725 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
@Alokih does not seem to work, at least we still see the old generated models with no loading screen when changing input and options.

Please make sure you test the preview that Netlify creates 🙂

**Comment by Alokih** [comment]
ok @jonaslagoni , I'll try to do it

**Review by devilkiller-ag — COMMENTED** [review]
When changing options, why we see blank on output side, instead we need `loading...` animation. Also you can notice that the `loading...` apears after the code is updated.

https://github.com/asyncapi/modelina/assets/43639341/53df862a-6c45-49c6-8fce-364788607a01

**Comment by Alokih** [comment]
Hey @devilkiller-ag I am trying to make it right, sorry for the time , if someone else ask to work on it you can unassign me

**Comment by jonaslagoni** [comment]
Closing as no progress, feel free to re-open if you get back to it @Alokih

**Pull request closed without merging**
