### PR TITLE
docs: fixed highlight in docs

### PR DESCRIPTION
**Pull request by officialasishkumar**
## Description
Fix highlight when selected and hovered in docs of modelina 😃 

## Related Issue
Fixes https://github.com/asyncapi/modelina/issues/1719

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by officialasishkumar** [comment]
@jonaslagoni Please take a look : )

**Comment by devilkiller-ag** [comment]
Hi @officialasishkumar, can you check why the tests are failing?

**Comment by officialasishkumar** [comment]
> Hi @officialasishkumar, can you check why the tests are failing?

PR title. Can you re-run the test

**Comment by jonaslagoni** [comment]
@devilkiller-ag can you take another look 🙂

**Review by devilkiller-ag — APPROVED** [review]

**Comment by devilkiller-ag** [comment]
Seems good to me!

**Pull request merged**
