### PR TITLE
fix: add Java contraints annotations at the field level

### PR DESCRIPTION
**Pull request by artur-ciocanu**
**Description**
Javax annotations should be applied at the field level to ensure that all the validation rules are properly invoked. Currently these are applied at the "getter" level.

**Related issue(s)**
Resolves https://github.com/asyncapi/modelina/issues/1066

### CODE REVIEW

**Comment by artur-ciocanu** [comment]
@jonaslagoni could you please take a look when you have a chance. Thank you.

**Review by jonaslagoni — COMMENTED** [review]
Just had to look it up as I couldn't remember which was the right way, but yea this is 100% correct 👍 

What is the reason for renaming the presets files? 🤔

**Comment by artur-ciocanu** [comment]
> Just had to look it up as I couldn't remember which was the right way, but yea this is 100% correct 👍
> 
> What is the reason for renaming the presets files? 🤔

I just wanted to have those reflect the name of the preset constants. If you think it should be reverted let me know and I'll revert.

**Comment by jonaslagoni** [comment]
@artur-ciocanu since most presets do not have the language as part of their name, I think it makes the most sense to keep it as is 🙂 But feel free to start a discussion in an issue 👍

**Comment by artur-ciocanu** [comment]
> @artur-ciocanu since most presets do not have the language as part of their name, I think it makes the most sense to keep it as is 🙂 But feel free to start a discussion in an issue 👍

@jonaslagoni I have reverted the renaming, I haven't checked other languages, but it makes sense to be consistent. Thank you.

**Pull request merged**
