### PR TITLE
chore(website): remove duplicate link from navbar

### LINKED ISSUE #1238: Remove duplicate navigation from navbar
#### Describe the bug
Currently in navbar there is a navitem named `modelina` which is doing the same thing as the logo 
#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
Just go to modelina.org and you will see it in navbar
- Screenshots
image

#### Expected behavior
We can remove the navitem modelina for now

### PR DESCRIPTION
**Pull request by Yasir761**
**Description**
Remove duplicate link from navbar.
**Related issue(s)**
Fixes #1238

### CODE REVIEW

**Comment by Savio629** [comment]
@Yasir761 you have to follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)
Just change the title of the pr to `fix: remove duplicate link from navbar`

**Review by jonaslagoni — APPROVED** [review]
LGTM :+1:

**Comment by jonaslagoni** [comment]
@all-contributors please add @Yasir761 for code

**Pull request merged**
