### PR TITLE
fix: merging CommonModel properties should not carry over properties to other models

### PR DESCRIPTION
**Pull request by kennethaasan**
**Description**

- Please check the Pet test in the MR. This fix makes sure that `CommonModel.mergeProperties` doesn't carry over any properties to other models when trying to merge Pet into multiple schemas.

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
I feel like we need a test that fails within the CommonModel tests that your change fixes 🤔 What do you think? 

https://github.com/asyncapi/modelina/blob/0a441c5c5bc29c97e21c7f25ff16068a2a94fb52/test/models/CommonModel.spec.ts#L457

The reason I am saying this is if the generators got split out from the core of Modelina in the future, we would have no tests to ensure that the properties are correctly merged.

Change looks fine though 👍

**Comment by kennethaasan** [comment]
@jonaslagoni, thanks for the quick review! Yes, that makes sense. I will add one now.

**Comment by kennethaasan** [comment]
@jonaslagoni , please check the test I added.

**Review by jonaslagoni — APPROVED** [review]
LGTM 👍

**Comment by jonaslagoni** [comment]
I need to fix a problem with the CI, but lets ignore it here 🙂

**Pull request merged**
