### PR TITLE
chore: add missing test dependency for docker

### PR DESCRIPTION
**Pull request by Ferror**
```
#13 21.46 npm ERR! If you are on Ubuntu, you can install with: 
#13 21.46 npm ERR! 
#13 21.46 npm ERR!  sudo apt install chromium
#13 21.46 npm ERR! 
#13 21.46 npm ERR! 
#13 21.46 npm ERR!  sudo apt install chromium-browser
#13 21.46 npm ERR! 
#13 21.46 npm ERR! ERROR: Failed to set up Chromium r1022525! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
```

I tried building the Docker Image on ARM. There are a couple of problems. The image is almost 4GB big 😢

### CODE REVIEW

**Comment by Ferror** [comment]
> Happy to have more improvements done if you have any suggestion 👍

I will iterate with small changes :)

**Comment by jonaslagoni** [comment]
https://github.com/all-contributors please add @Ferror for bug, infra

**Comment by jonaslagoni** [comment]
@all-contributors please add @Ferror for bug, infra

**Pull request merged**
