### PR TITLE
feat: add modelName to warning log

### PR DESCRIPTION
**Pull request by gitankit7**
refactor: Adding modelName to the warning log.

## Description
refactor: Added modelName to the warning log to explicitly mention the model in the logs which is running into a warning state while generating models

## Checklist
- [ ✅  ] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ✅  ] Tests have been added or updated to cover the changes.
- [ ✅  ] Documentation has been updated to reflect the changes.
- [ ✅ ] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Review by jonaslagoni — DISMISSED** [review]
🤙

**Comment by jonaslagoni** [comment]
@gitankit7 got a lint error ✌️

**Comment by gitankit7** [comment]
> @gitankit7 got a lint error ✌️

@jonaslagoni  - Linter should be happy now. :)

**Review by jonaslagoni — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@all-contributors please add @gitankit7  for code

**Pull request merged**
