### PR TITLE
feat!: adds inheritance with interfaces for java

### PR DESCRIPTION
**Pull request by kennethaasan**
**Description**

This MR adds inheritance with interfaces for Java. Our Java users are complaining about missing interfaces for schemas that include `allOf`. Unlike TypeScript, In Java, it's problematic to use classes without interfaces if lots of classes are similar. This is an attempt to fix that. This is a difficult one to solve in a good way, and the arguments in #108 describe that, but we need to find a way to improve the generated code for Java. 

**Related issue(s)**

See also #108 and #1613

### CODE REVIEW

**Comment by kennethaasan** [comment]
@dlkj, perhaps you have some input here as a Java user who also might need this? Keep in mind that this is still a draft, but something we're prioritizing at the moment.

**Comment by kennethaasan** [comment]
@jonaslagoni, I'm also eager to hear your input on how this can be solved. Am I on the right track, or should this be solved in a different way?

**Review by jonaslagoni — COMMENTED** [review]
Honestly looks pretty good to me 🤔 

Looking forward to seeing this in C# and TypeScript.

My only concern would be how it handles multiple inheritance when`allOf` has multiple entries, in languages that only allow a single one? 🤔

**Comment by kennethaasan** [comment]
Thanks for your feedback! I'm still working through issues we've found by generating code with these changes in our own codebase. Once I'm happy with the output I'll split this draft into multiple smaller PRs.

@jonaslagoni, I think that should be the responsibility of the generator of the language. E.g. in Java, it's natural to use interfaces because it supports multiple, while extend only supports one. I think lots of other programming languages are in a similar situation as Java.

**Comment by kennethaasan** [comment]
@jonaslagoni, please review

**Review by jonaslagoni — APPROVED** [review]
👍

**Pull request merged**
