### PR TITLE
test: added test for PHP constraint

### PR DESCRIPTION
**Pull request by Min2who**
## Description
Added test for php constraint

## Related Issue
fix: #1668

### CODE REVIEW

**Comment by Min2who** [comment]
@jonaslagoni can you review it?

**Comment by jonaslagoni** [comment]
@Ferror do you have time to take a look at this?

**Review by Ferror — COMMENTED** [review]
I will always props extra tests. Thank you @Min2who. Could you please fix the Sonar Cloud issues about unused imports? I will later approve and merge it :)


Screenshot 2023-12-27 at 19 47 31

**Review by Ferror — APPROVED** [review]

**Pull request merged**
