### PR TITLE
chore: chang code examples for some operations on generated models

### PR DESCRIPTION
**Pull request by sagarkori143**
closes: #1751 

These are the current code examples written for performing some operations on generated models:
##### 1) In README.md :

image

##### 2) On website landing page:

image

#### I have changed them to this:

```
for (const model in models) { 
  const generatedCode = model.result;
  const dependencies = model.dependencies;
  const modeltype = model.type;
  const modelName = model.modelName;
}
```

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
@sagarkori143 Looks good to me. Can you change the PR Title and Description to make it more descriptive?

**Comment by devilkiller-ag** [comment]
Hi @sagarkori143, can you resolve the failure of pr lint check.

**Comment by sagarkori143** [comment]
@devilkiller-ag But it's showing me All checks have passed

**Comment by devilkiller-ag** [comment]
I got one check fail. 

Let me re-run the check.

**Comment by sagarkori143** [comment]
@devilkiller-ag What happened in re runs?

**Comment by devilkiller-ag** [comment]
Yup, they passed now. Everything looks good to me.

**Review by devilkiller-ag — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@devilkiller-ag remember to only use `fix`, `feat` when it comes to changes to the code for the Modelina library 🙂

**Pull request merged**
