### PR TITLE
chore(website): add System.Text.Json serialization support in the playground

### LINKED ISSUE #1175: Add System.Text.Json serialization support in the Playground
#### Reason/Context
For the C# generator, you can [choose to make the model generate serialization support for the System.Text.Json library](https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#using-native-systemtextjson), this should be possible in the playground as well.

To achieve this the following needs to change:
- Add the option `csharpIncludeJson` to [the list of options](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/types/index.ts#L19) where the type is `boolean`
- Make sure we show the options being provided in [the generator code output of the playground](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts#L4).
- Adapt the UI to [include a checkbox](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use the [following code as baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L61)
- Add a react handler to handle when the [checkbox changes](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use [following code as a baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L26).
- Adapt the backend serverless function to use the [new option during the generation phase](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/pages/api/functions/CSharpGenerator.ts#L13)

Happy to help even further in case you need it! Ping me here in the issue or in the AsyncAPI slack channel 👋

### PR DESCRIPTION
**Pull request by kaushik-rishi**
**Description**
- add System.Text.Json serialization support in the playground

**Related issue(s)**
- Fixes #1175

### CODE REVIEW

**Comment by jonaslagoni** [comment]
You still have some outstanding changes that is needed, the website wont currently build 🙂

**Comment by kaushik-rishi** [comment]
> You still have some outstanding changes that is needed, the website wont currently build slightly_smiling_face

I have indentified some issues, which i'll fix.
Please don't tell me what's the issue yet :smile: 
I'd like to try brainstorming and figuring it out on my own.

**Comment by kaushik-rishi** [comment]
Also, why's the server even running when there're compilation errors on my local ? 🥲
Can you help me figure this out ?

**Comment by jonaslagoni** [comment]
> @jonaslagoni why don't i see these errors when i run npm run build in my local machine ?

Are you running the build command under the website? 

Hard for me to pinpoint anything by saying it worked locally 😄 There can be so many reasons why 🙂

**Comment by kaushik-rishi** [comment]
> > @jonaslagoni why don't i see these errors when i run npm run build in my local machine ?
> 
> 
> 
> Are you running the build command under the website? 
> 
> 
> 
> Hard for me to pinpoint anything by saying it worked locally 😄 There can be so many reasons why 🙂 

reasonable 🙂
I'll send more context. A screen recording clip or something which you help.

**Comment by jonaslagoni** [comment]
So far it seems like you have all the things in place 🤔

**Review by jonaslagoni — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@all-contributors please add @kaushik-rishi for code, design

**Comment by kaushik-rishi** [comment]
This was a very great learning experience and i feel beginners will learn a lot about a lot of different things (type system, api routes, component structure, context api) by solving one such issue. I'm thereby attaching some notes :slightly_smiling_face:  which might help others landing here. Thanks @jonaslagoni :heart:

**Comment by kaushik-rishi** [comment]
Playground Component
--------
- we have a `config` state, consisting of all the options of that can be given to all the languages, with their default values (type: `ModelinaOptions`)
- `render()` method, parses the query params for persistence of the state between tab switches (generated code, options) (type: `ModelinaQueryOptions`)
- We have the `PlaygroundOptions` component, embedded into a tree of components which are basically Context providers for different language options

`/playground/options/CSharpGeneratorOptions.tsx` Component
--------
- implement `onChangeIncludeJson` function
- bind the function to `this` inside of the constructor for binding the component context
- Add the option here and bind it with the onChange function and the state variable


`/types/index.ts` Type definitions
---------
- We add the newly added options into `ModelinaCSharpOptions` and `ModelinaCSharpQueryOptions`
- the types (interfaces technically) `ModelinaOptions` and `ModelinaQueryOptions` extend the types of their respective language choices, so no need to worry about updating those types with your newly added options.

`/pages/api/functions/CSharpGenerator.ts` NextJS api endpoint
---------
- Code to actually generate the models, uses the modelina library and the presets

`/helpers/GeneratorCode/CSharpGenerator.ts` Component
---------
- function used to generate the generator code 🙂 (ik it's funny)
- add respective code needed to change the generator code (could be just adding a preset to the template literal)

**Comment by jonaslagoni** [comment]
Might be nice to include these in the website docs 🤔 What do you think @kaushik-rishi?

**Comment by jonaslagoni** [comment]
@kaushik-rishi meant your description of the components in the website for other to get a quick start 😄

**Comment by kaushik-rishi** [comment]
@jonaslagoni 
Not sure if you'd want to have something of that sort on the website 🙂

Just incase you want to have it, I'll make a better documentation of state management inside the modelina-website and the description of folder structure in a proper manner. If that would help I'd be more than happy to do it 🙂

**Comment by jonaslagoni** [comment]
Not on the website, but here: https://github.com/asyncapi/modelina/blob/master/modelina-website/README.md 🙂

**Pull request merged**
