### PR TITLE
fix: additional content presets for PHP enums are not applied

### PR DESCRIPTION
**Pull request by markuspoerschke**
When using the preset option `additionalContent`, the content was not added to the PHP enum.

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Thanks for taking the time and providing a fix @markuspoerschke 👍 

@Ferror do you have time to review this?

**Comment by Ferror** [comment]
> Thanks for taking the time and providing a fix @markuspoerschke 👍 
> 
> 
> 
> @Ferror do you have time to review this?

Will look into that next week :)

**Review by Ferror — APPROVED** [review]

**Comment by jonaslagoni** [comment]
Remember you can use this command as well @Ferror to merge stuff you reviewed 🙂

**Comment by jonaslagoni** [comment]
@all-contributors please add @markuspoerschke for code, test

**Pull request merged**
