### PR TITLE
feat: ensure C# types are generated with 'partial' modifier.

### PR DESCRIPTION
**Pull request by RowlandBanks**
## Description

Adds `partial` modifier to generated types.

## Related Issue

* Partial types in C#: https://github.com/asyncapi/modelina/issues/1776

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
I don't think any documentation changes are required?

- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
@RowlandBanks remember to update the examples as well, there are a command for it ✌️

**Comment by RowlandBanks** [comment]
@jonaslagoni I've updated the examples as requested, thanks.

There are [4 Actions](https://github.com/asyncapi/modelina/actions?query=branch%3Aadd-partial-modifier-to-csharp-types)  that still need to run:

image

but it looks like they are awaiting approval from a maintainer to trigger. Is there anything I need to do to progress this?

**Review by jonaslagoni — APPROVED** [review]
@RowlandBanks yep all good, all test is flying with colors ✌️

Thanks for taking the time to contribute this 💪

**Comment by jonaslagoni** [comment]
@all-contributors please add @RowlandBanks for code, test

**Pull request merged**
