### PR TITLE
chore: add artur-ciocanu as scala champion

### PR DESCRIPTION
**Pull request by jonaslagoni**
With the newly added Scala generator (https://github.com/asyncapi/modelina/pull/1665), @artur-ciocanu wanted to remain as champion for it 💪🔥

cc @kennethaasan @magicmatatjahu @Ferror @leigh-johnson @Samridhi-98 @devilkiller-ag any objections?

Lazy consensus will be used with @artur-ciocanu acceptance after 1 week from this PR creation 🙂

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@artur-ciocanu just for a good measure, do you mind also giving you approval ✌️

**Review by devilkiller-ag — APPROVED** [review]

**Comment by devilkiller-ag** [comment]
Welcome @artur-ciocanu ✨

**Comment by artur-ciocanu** [comment]
> @artur-ciocanu just for a good measure, do you mind also giving you approval ✌️

Hey @jonaslagoni I approve, not sure what 

> @artur-ciocanu just for a good measure, do you mind also giving you approval ✌️

Hey @jonaslagoni I approve, not sure if anything more formal is required. Just let me know.

**Comment by jonaslagoni** [comment]
@artur-ciocanu by reviewing the PR (see files changed) you should be able to approve it, but verbal is fine as well 😄👌

**Review by Ferror — APPROVED** [review]

**Review by artur-ciocanu — APPROVED** [review]
LGTM!

**Review by Ferror — APPROVED** [review]

**Comment by jonaslagoni** [comment]
Welcome among the champions @artur-ciocanu, happy to have you on board 🎉 Checkout the champions guideline here: https://github.com/asyncapi/modelina/blob/master/docs/champions.md

If you have any questions you can always reach out ✌️

**Comment by jonaslagoni** [comment]
@all-contributors please add @artur-ciocanu for maintenance

**Comment by derberg** [comment]
@artur-ciocanu are you interested in joining us also as TSC member, like https://github.com/asyncapi/community/pull/993 ?

**Pull request merged**
