### PR TITLE
feat: add Modelina CLI

### PR DESCRIPTION
**Pull request by devilkiller-ag**
## Description
Modelina and integrate it with AsyncAPI CLI

## Related Issue
Related to issue #1724 and PR #1785 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

## Additional Notes
This PR is the extension of PR #1785. The initial base has been built from Async API CLI. Now we need to add rectify all the tests, do clean-ups, and integrate this Modelina CLI with Modelina CLI.

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
cc: @jonaslagoni

**Comment by jonaslagoni** [comment]
Perfect @devilkiller-ag 👌

**Comment by devilkiller-ag** [comment]
@jonaslagoni, so what should be our next step?

**Comment by jonaslagoni** [comment]
@devilkiller-ag we each can now make PRs that target the `cli` branch, and we just collaborate :v: You continue exactly as you have been doing, lets just stick to small changes so we dont duplicate work as much as possible 🙂How does that sound?

**Comment by devilkiller-ag** [comment]
Okay, then I will start with working on tests, and see why it's failing?

**Comment by jonaslagoni** [comment]
@devilkiller-ag alright 👍

**Comment by devilkiller-ag** [comment]
Just merged the cleanup, what's the next thing to tackle 👀

**Comment by jonaslagoni** [comment]
Retarget the PR to `next` so we can release it ASAP and do a bit of trial running making sure everything works before it enters `master`.

**Comment by jonaslagoni** [comment]
@devilkiller-ag I actually see it as merge ready 🤔 How about you?

**Comment by devilkiller-ag** [comment]
Seems good to me! I will merge this to `next`.

**Comment by jonaslagoni** [comment]
@devilkiller-ag they can safely be ignored, has nothing to do with these changes

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, when we are going to merge this?

**Comment by jonaslagoni** [comment]
Wanted to wait few days to give the other maintainers some time to review it, but since it's `next` lets see how it behaves :v:

**Pull request merged**
