### PR TITLE
refactor: replace `switch` statements with `if else`.

### LINKED ISSUE #236: Ensure consistancy between switch statements
#### Reason/Context
Currently, we have very small switch statements which are considered a [code smell by sonarcloud](https://sonarcloud.io/project/issues?id=asyncapi_generator-model-sdk&open=AXjKlPuxVLGRvzF4eQNt&resolved=false&rules=typescript%3AS1301). We should fix all of these issues so we get rid of them.

Make sure to read the readme file [how to contribute](https://github.com/asyncapi/modelina#contributing), if you have any questions feel free to reach out here, or in our [Slack](https://www.asyncapi.com/slack-invite).

### PR DESCRIPTION
**Pull request by Blakelist7**
This commit replaces `switch` statements with `if else` since there are very small `switch` statements at some places which have only 1 case.

Signed-off-by: Kanwal Singh <kanwal.88singh@gmail.com>

**Related issue(s)**

Fixes #236

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@Blakelist7 do you want me to point you in the right direction or tell you straight up where the error is? 🤔 

Depends from person to person how they want to be helped, which is why I am asking 🙂

**Comment by Blakelist7** [comment]
Let's go forward in the right direction first, then if it does not work. I still have the other option, right ? 😄

**Comment by jonaslagoni** [comment]
> Let's go forward in the right direction first, then if it does not work. I still have the other option, right ? 😄

Of course 😄 

Take a look at the switch statements and what values are evaluated vs what if statements are created in its place 🙂

**Comment by Blakelist7** [comment]
In switch statements we are returning something after selecting a particular case but in if else statements I am not selecting, am just comparing it with a const value, right?

**Comment by jonaslagoni** [comment]
It is not a matter of return statements, but the values that are evaluated in the switch statement vs the expression you added in the if statement. 

As the tests point out it is a change that happened in the Java enum generator (as it is the enum values that are wrongfully generated) 🙂

**Comment by Blakelist7** [comment]
I think there was just a minor issue after fixing that everything worked smooth :). BTW Thanks.

**Review by jonaslagoni — APPROVED** [review]
Awesome, well done 🎉 thanks!

**Comment by jonaslagoni** [comment]
@all-contributors please add @Blakelist7 for code

**Pull request merged**
