### PR TITLE
style(website): redesign homepage

### PR DESCRIPTION
**Pull request by devilkiller-ag**
## Description
This PR is to redesign the hero of the website as discussed in issue #1293.  

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
The code boxes are not scrollable on mobile 🤔

**Comment by devilkiller-ag** [comment]
> The code boxes are not scrollable on mobile 🤔

Are you talking about the code boxes in the usage section?

**Comment by jonaslagoni** [comment]
Up to you @devilkiller-ag, just let me know when to review again 😄

**Comment by devilkiller-ag** [comment]
Hey @jonaslagoni, the usage section is almost complete. Can it also be included in the v3 release if I complete it today?

**Comment by jonaslagoni** [comment]
There is nothing special about Modelina v3 so everything fixed before the release will of course be included 🙂 It's a continuous effort to improve the tool so yea 👍

**Comment by devilkiller-ag** [comment]
@jonaslagoni I have redesigned the usage section too under this PR!

**Review by jonaslagoni — APPROVED** [review]
Looks amazing @devilkiller-ag 🔥

**Pull request merged**
