### PR TITLE
docs: fix the contributing link in readme

### LINKED ISSUE #1224: The link to the contributors on Readme is not working properly
#### Describe the bug
The link to the contributors on Readme is not working properly

#### How to Reproduce

https://user-images.githubusercontent.com/91362589/230564123-3563fdda-26fd-453a-ae74-fa315bf429e7.mp4

### PR DESCRIPTION
**Pull request by Savio629**
**Description**
Fixed the contributing link in readme

https://user-images.githubusercontent.com/91362589/230572730-c84c20d7-8090-4f85-9d0e-a1321204d243.mp4

<br>

**Related issue(s)**
Fixes #1224

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Nice catch 👍 

This is actually automatically generated by `npm run generate:readme:toc`, to fix this we have to change the heading of `Contributors ✨` instead.

Think removing `✨` should be enough 🤔

**Comment by Savio629** [comment]
@jonaslagoni 
Done 👍

**Review by jonaslagoni — APPROVED** [review]
LGTM 👍

**Review by jonaslagoni — APPROVED** [review]

**Pull request merged**
