### PR TITLE
fix: use type as a fallback if no special handling for format is provided

### LINKED ISSUE #533: Java generation - support for 'format' classifier
In the specification when I define my schema I can define a format e.g. datetime, email, etc.

At the moment when I generate with modelina java DTOs properties having a format defines are given a type of "Object".

Having the generated code support the api specified constraints (string = email, or string is to be interpreted as a date) is important for correctness and consistency of how an API is used.

Below is an example illustrating such an issue with date format.

image

### PR DESCRIPTION
**Pull request by 200Puls**
**Description**

- Add type as a fallback if no special handling for format has been provided.
- Fixes #533 

**Related issue(s)**

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
You have some tests that are failing @200Puls 🙂 

Might just be the snapshots needs to be updated.

**Comment by 200Puls** [comment]
Hi @jonaslagoni,
I have updated the snapshots and locally all tests are green now.

**Comment by 200Puls** [comment]
@jonaslagoni  Sorry about the formatting. I just pushed the changes again and corrected the formatting.

**Review by jonaslagoni — APPROVED** [review]
👍

**Pull request merged**
