### PR TITLE
feat: add Newtonsoft serialization support in the playground

### LINKED ISSUE #1176: Add Newtonsoft serialization support in the Playground
#### Reason/Context
For the C# generator, you can [choose to make the model generate serialization support for the Newtonsoft library](https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#using-newtonsoftjsonnet), this should be possible in the playground as well.

To achieve this the following needs to change:
- Add the option `csharpIncludeNewtonsoft` to [the list of options](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/types/index.ts#L19) where the type is `boolean`
- Make sure we show the options being provided in [the generator code output of the playground](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts#L4).
- Adapt the UI to [include a checkbox](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use the [following code as baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L61)
- Add a react handler to handle when the [checkbox changes](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use [following code as a baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L26).
- Adapt the backend serverless function to use the [new option during the generation phase](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/pages/api/functions/CSharpGenerator.ts#L13)

Happy to help even further in case you need it! Ping me here in the issue or in the AsyncAPI slack channel 👋

### PR DESCRIPTION
**Pull request by kaushik-rishi**
**Description**
- add newtonsoft serialization to c# in playground

**Related issue(s)**
Fixes #1176

### CODE REVIEW

**Comment by kaushik-rishi** [comment]
Also, @jonaslagoni do these come under `chore` or under `feat`.
I somewhere came accross some document mentioning the clear difference between each of these options, but i seem to have lost track of the contribution guidelines having details of commit headers. It'd be great if you could provide me it's reference.

**Comment by jonaslagoni** [comment]
For website changes, everything is `chore(website)` 🙂 

You seem to be missing a few changes, see more in the issue: https://github.com/asyncapi/modelina/issues/1176 🙂

**Comment by kaushik-rishi** [comment]
@jonaslagoni i've identified them, will work on them.

**Comment by jonaslagoni** [comment]
You have some merge conflicts to solve after your last PR was merged 🙂

**Comment by jonaslagoni** [comment]
Ping ping @kaushik-rishi 🙂

**Pull request closed without merging**
