### PR TITLE
refactor: remove code smells from `JavaRenderer`

### LINKED ISSUE #235: Solve code smells for JavaRenderer
#### Reason/Context
Based on the following [sonarcloud issues](https://sonarcloud.io/project/issues?fileUuids=AXjKlPosVLGRvzF4eQL5&id=asyncapi_generator-model-sdk&resolved=false) we should remove all code smells from [JavaRenderer](https://github.com/asyncapi/modelina/blob/master/src/generators/java/JavaRenderer.ts).

Make sure to read the readme file [how to contribute](https://github.com/asyncapi/modelina#contributing), if you have any questions feel free to reach out here, or in our [Slack](https://www.asyncapi.com/slack-invite).

### PR DESCRIPTION
**Pull request by Blakelist7**
**Description**
This PR fixes/resolves 3 code smells from `JavaRenderer.ts`. 

Signed-off-by: Kanwal Singh <kanwal.88singh@gmail.com>

**Related issue(s)**

Fixes #235

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Awesome @Blakelist7 🎉 Only one comment, please use camelcase for variable names 🙂

**Comment by Blakelist7** [comment]
> Awesome @Blakelist7 tada Only one comment, please use camelcase for variable names slightly_smiling_face

We use camelCase, right?

**Comment by jonaslagoni** [comment]
> We use camelCase, right?

yes 😄

**Review by jonaslagoni — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
