### PR TITLE
feat: add dependency manager

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR merges the final code into `next`, which got started in https://github.com/asyncapi/modelina/pull/947

**Related issue(s)**
Closes https://github.com/asyncapi/modelina/issues/851

### CODE REVIEW

**Comment by jonaslagoni** [comment]
You can see the changes I applied ontop of all the PRs that has already been accepted here: https://github.com/asyncapi/modelina/pull/1063/commits/5ab42aabe9cdde22bd53d83dfd343d1ccd9a4086

I changed the following:
- Added generator documentation for how options work
- Fixed all build and test errors
- Fixed an error where the dependency manager was not respected (converted from Class to Object) when merging options.
- For TypeScript I removed the ExportKeywordPreset and instead export the models with `export { MODEL };` instead of adding the export keyword before the class `export class MODEL {};`.

**Comment by jonaslagoni** [comment]
I want to merge https://github.com/asyncapi/modelina/pull/1074 before merging this one.

/dnm

**Comment by jonaslagoni** [comment]
Blocked by https://github.com/asyncapi/modelina/pull/1083

**Review by magicmatatjahu — APPROVED** [review]

**Pull request merged**
