### PR TITLE
chore(website): wrong import directory for docs images

### LINKED ISSUE #1700: [Docs Bug 🐞 report]: Transformation stages picture missing
### Describe the bug you found in AsyncAPI Docs.

I noticed that the transformation stages image is missing in the input-processing section of the documentation. This image is crucial for understanding the input processing flow, and its absence is causing confusion for users.

### Attach any resources that can help us understand the issue.

https://modelina.org/docs/input-processing link to docs

isssue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by moritzkalwa**
## Description
The import directory in 'build-docs.js' did not match the one set in package.json (`"copy:docs:img": "cp -r ../docs/img public/img/docs"`)

## Related Issue
Fixes #1700 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@devilkiller-ag can you have a look :v:

**Comment by devilkiller-ag** [comment]
Looks Good to me! Thanks @moritzkalwa!

**Review by devilkiller-ag — APPROVED** [review]
Looks Good to me! Thanks @moritzkalwa!

**Pull request merged**
