### PR TITLE
fix: prettier configuration added

### LINKED ISSUE #646: Add .prettierrc to project
#### Reason/Context

When working on a custom Go preset, ESLint was complaining about listing rules I was violating. Somehow I couldn't configure VSCode's prettier/formatter integration to stop formatting code when there is no prettierrc.

Overall I think it would help contributors quite a bit to have prettier on the project. Having to manually deal with formatting is a pain and prettier is pretty standard and well supported.

#### Description

- Add prettier as a dependency
- Add a `.prettierrc`
- Update `.eslintrc` to disable rules that are handled by prettier.

### PR DESCRIPTION
**Pull request by akshatnema**
**Description**

Added `.prettierrrc` file to add the Prettier configuration along with ESlint configuration for typescript.

**Related issue(s)**
Resolves #646

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Awesome 🎉 @akshatnema do you mind re-targetting `next`? 🙂 I dont think you get any conflicts 🙂

**Comment by akshatnema** [comment]
@jonaslagoni I added the script `npm run format` in `package.json` file to format the TS files and linked it with ESlint. I made a config for prettier but want a review from you in order to add extra options to the file. Also, I haven't formatted the files in the repo using the script. Let's finalise the config first and then we will update all the files according to the configuration.

Prettier Config Options - https://prettier.io/docs/en/options.html

**Comment by akshatnema** [comment]
> do you mind re-targetting next?

Sorry I didn't get that. Can you elaborate on what I need to re-target?

**Comment by jonaslagoni** [comment]
> @jonaslagoni I added the script npm run format in package.json file to format the TS files and linked it with ESlint. I made a config for prettier but want a review from you in order to add extra options to the file. Also, I haven't formatted the files in the repo using the script. Let's finalise the config first and then we will update all the files according to the configuration.

Thats perfect 👌 Lets wait yes!

>  Sorry I didn't get that. Can you elaborate on what I need to re-target?

Yea, nwm, it's not possible 😄 Most development happen on the `next` branch, but since you based your changes on `master` it creates a bit of friction. So I will apply the changes later instead 🙂

**Comment by akshatnema** [comment]
> Yea, nwm, it's not possible smile Most development happen on the next branch, but since you based your changes on master it creates a bit of friction. So I will apply the changes later instead :slightly_smiling_face:

@jonaslagoni Do you want to merge this change in `next` branch? I can readily do that but I have to then dissolve this PR and make a new one targeting from `next`.

**Comment by jonaslagoni** [comment]
> @jonaslagoni Do you want to merge this change in `next` branch? I can readily do that but I have to then dissolve this PR and make a new one targeting from `next`.

Up to you 🙂 I have to merge many of the other changes that have happen on the `master` branch any way, but I would then not have to do this change, so that would definitely be nice 😄

**Pull request closed without merging**
