### PR TITLE
fix: multi line descriptions for the pydantic preset in python

### LINKED ISSUE #1058: Python Pydantic improvements
##### Field.alias
It seems that for Pydantic `Field` typing use of `property.description` as an `alias` is incorrect, and `property.name` or some other field should be used instead. Current implementation:
```typescript
const PYTHON_PYDANTIC_CLASS_PRESET: ClassPresetType<PythonOptions> = {
  property(params) {
    const type = params.property.required
      ? params.property.property.type
      : `Optional[${params.property.property.type}]`;
    const alias = params.property.property.originalInput['description']
      ? `alias='${params.property.property.originalInput['description']}'`
      : '';

    return `${params.property.propertyName}: ${type} = Field(${alias})`;
  }
};
```
Possible fix:
```typescript
    const alias = params.property.property.originalInput['name']
      ? `alias='${params.property.property.originalInput['name']}'`
      : '';
```
##### Field.description
Introduce support for setting a Field's `description` from `property.description`

##### Extra.forbid
For models declaring `additionalProperties` as false enable native validation:
```python
from pydantic import BaseModel, Extra


class Model(BaseModel, extra=Extra.forbid):
    a: str
```

#### Description
- Change from `description` to `name` when setting `Field.alias` will be a breaking change, but it's more of a misuse or a bug in the current state.

### PR DESCRIPTION
**Pull request by kennethaasan**
**Description**

- fixes multi-line descriptions for the Pydantic preset in Python

**Related issue(s)**

Fixes #1058

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Need some test snapshots updated 🙂 

Looks good otherwise 👍

**Comment by kennethaasan** [comment]
> Need some test snapshots updated 🙂
> 
> Looks good otherwise 👍

Ups, updated now 😄

**Review by jonaslagoni — APPROVED** [review]
🔥

**Pull request merged**
