### PR TITLE
fix: update default Kotlin renderer to make non-required properties nullable

### PR DESCRIPTION
**Pull request by micro-jumbo**
**Description**

- Update default Kotlin renderer to make non-required properties nullable and `null` by default.
- Updated snapshots
-  
**Related issue(s)**
Fixes#1273

### CODE REVIEW

**Comment by LouisXhaferi** [comment]
This should fix #1273

**Comment by LouisXhaferi** [comment]
lgtm apart from the failing check.

I'd still want to wait for feedback from @jonaslagoni on how to handle breaking changes.

**Comment by jonaslagoni** [comment]
I would definitely target `next`, cause if a consumer of a model uses them with the expectation of properties being required it would break their code (even though this is the output🙂)

**Comment by micro-jumbo** [comment]
@LouisXhaferi @jonaslagoni 
Thanks guys for your review. I pushed additional change to fix the linter issue. Is there anything more I should do to get it merged?

**Comment by jonaslagoni** [comment]
You need to retarget the PR towards `next`, I don't think you will get any issues, but not entirely sure, and then mark the PR as breaking i.e. `fix!:` instead and then add an entry in https://github.com/asyncapi/modelina/blob/next/docs/migrations/version-1-to-2.md that it breaks for Kotlin 🙂

**Comment by micro-jumbo** [comment]
Due to conflicting files after retargeting to `next` closing this one in favour of #1277

**Pull request closed without merging**
