### PR TITLE
feat!: release v3

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This is a placeholder for the release of the `next` branch for v3.

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Hey @kennethaasan @magicmatatjahu @Samridhi-98 @devilkiller-ag @Ferror @leigh-johnson @artur-ciocanu 

Planning to release v3 at the end of the month, any objections? 

It is also a heads up for you folks in case you want any breaking changes included 🙂

**Comment by devilkiller-ag** [comment]
Okay from my side, the redesign of the website will be completed by that time.

**Comment by jonaslagoni** [comment]
As soon as https://github.com/asyncapi/modelina/pull/1754 and https://github.com/asyncapi/modelina/pull/1757 have been merged I will release v3 🙂

**Comment by jonaslagoni** [comment]
@kennethaasan @magicmatatjahu @Samridhi-98 @devilkiller-ag @Ferror @leigh-johnson @artur-ciocanu planning to do the release tomorrow, last chance for review and comments 🙂

**Pull request merged**
