### PR TITLE
chore: add Scala runtime tests

### PR DESCRIPTION
**Pull request by artur-ciocanu**
## Description
Adding runtime tests for Scala generator

## Related Issue
https://github.com/asyncapi/modelina/issues/1743

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by artur-ciocanu** [comment]
@jonaslagoni this is WIP, I wasn't able to run the commands:
```
$ npm run generate:runtime:scala
```
From local box, I keep getting errors like:
```
Module '"../../lib/cjs"' has no exported member 'SCALA_DEFAULT_PRESET'.
```
I am not sure if my setup is broken or am I doing something stupid.

Any help is much appreciated. Thank you 🙇

**Comment by jonaslagoni** [comment]
@artur-ciocanu remember to run build:prod before running the script as it uses the mode runtime and need cjs transpiled files

**Review by jonaslagoni — APPROVED** [review]
👍

**Pull request merged**
