### PR TITLE
refactor(website): rewrite class-based react components to functional components in modelina website

### LINKED ISSUE #1648: Rewrite Class-Based React Components to Functional Components in Modelina Website
The current codebase of the Playground Generator Options, Docs, and Examples Components of the Modelina Website contains class-based react components. We should update the code base to use functional components and hooks at all places. This will result in cleaner, easier-to-understand components compared to class components. This issue is to track my work on this.

### PR DESCRIPTION
**Pull request by devilkiller-ag**
**Description**
The current codebase of the Playground Generator Options, Docs, and Examples Components of the Modelina Website contained class-based react components. I have updated the code base to use functional components and hooks at all places. This results in cleaner, easier-to-understand components compared to class components.

**Related issue(s)**
Fixes #1648

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
You got a build error 🙂 https://app.netlify.com/sites/modelina/deploys/6577f46ad08e2b00086338de

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, It was due to different types of query values for different options, I have resolved it.

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, It seems the pull bot forcely pushed the master branch to my branch and all changes made by me are gone. Due to this I also can't see the review you requested. Can you suggest why this happened and what changes you requested?

**Comment by jonaslagoni** [comment]
@devilkiller-ag ehh, I have not seen this before? 🧐

**Comment by jonaslagoni** [comment]
Can you re-create the branch and the changes? 🤔

**Comment by devilkiller-ag** [comment]
Yeah Sure, but it just scared me 💀😂

**Comment by devilkiller-ag** [comment]
@jonaslagoni I created a new PR from new branch: https://github.com/asyncapi/modelina/pull/1655

**Pull request closed without merging**
