### PR TITLE
chore(website): improved the layout of the lower section of playground

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**

- improved the lower section of the playground

**Related issue(s)**

#1346

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Gonna follow up in https://github.com/asyncapi/modelina/issues/1346

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 just converting this PR to a draft until you are ready for it to be reviewed 🙂

**Comment by sambhavgupta0705** [comment]
cc: @jonaslagoni

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
This layout does not work well with multiple models being generated 🤔 

image

**Comment by sambhavgupta0705** [comment]
Ohh I didn't know we can have multiple models .
We can try making it as a dropdown menu. I will look into it today

**Comment by sambhavgupta0705** [comment]
@jonaslagoni for now we can go with this layout

**Comment by sambhavgupta0705** [comment]
@jonaslagoni

**Review by jonaslagoni — APPROVED** [review]
Sorry for the delay @sambhavgupta0705. Looks good to me 👍 Can't wait for the rework options 🔥

**Comment by sambhavgupta0705** [comment]
> Sorry for the delay @sambhavgupta0705. Looks good to me +1 Can't wait for the rework options fire

Yeahh Jonas ,will be sharing a design soon.

**Pull request merged**
