### PR TITLE
feat: add namingConvention option and pass generator to renderers

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- Add `namingConvention` option to options: naming for type and single property
- Pass `generator` to `renderers`
- Add `collectionType` option to Java generator to render `List<type>` or `type[]` signature for collections
- Add unit tests
- Update renderers and use `namingConvention` everywhere
- Update docs

**Related issue(s)**
Resolves https://github.com/asyncapi/generator-model-sdk/issues/124
Resolves https://github.com/asyncapi/generator-model-sdk/issues/126

### CODE REVIEW

**Review by jonaslagoni — COMMENTED** [review]
Are there any tests that verify the functionality? 🤔 Can't seem to locate them if there is.

**Comment by magicmatatjahu** [comment]
@jonaslagoni Here https://github.com/asyncapi/generator-model-sdk/pull/129/files#diff-845d99a72c900f84899b498d440c7615cbbaa031ea8f19e8124bd0cf740d5fafR49 and https://github.com/asyncapi/generator-model-sdk/pull/129/files#diff-845d99a72c900f84899b498d440c7615cbbaa031ea8f19e8124bd0cf740d5fafR30

PR has changed everywhere namingConvention from inline `FormatHelpers...` to new one, so it also shows that the old tests pass without problems :)

**Review by jonaslagoni — APPROVED** [review]
👍

**Comment by magicmatatjahu** [comment]
@jonaslagoni I added `collectionType` to Java generator and updated docs. Could you check it again?

**Review by jonaslagoni — APPROVED** [review]
LGTM 👍

**Comment by jonaslagoni** [comment]
@magicmatatjahu can we merge this?

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
A little code smell before merging.

**Pull request closed without merging**
