### PR TITLE
docs: update c# dependency

### LINKED ISSUE #915: Document C# preset CSHARP_JSON_SERIALIZER_PRESET require Microsoft.CSharp dependency
#### Describe the bug
When using the preset `CSHARP_JSON_SERIALIZER_PRESET` it requires (for additionalProperties) the dependency Microsoft.CSharp version 4.7 I believe.

This needs to be added to the list of dependencies for the preset here: https://github.com/asyncapi/modelina/blob/next/docs/languages/Csharp.md#using-native-systemtextjson

Remember to target the `next` branch for any changes.

Feel free to reach out if you need any clarifications, either here or on slack!

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**

This PR updates the dependency of C# 

**Related issue(s)**

Resolves #915

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 as this is a docs fix, do you mind changing the title to `docs: ...`🙂

**Comment by sambhavgupta0705** [comment]
> @sambhavgupta0705 as this is a docs fix, do you mind changing the title to `docs: ...`slightly_smiling_face

ohh sorry forgot about it,making the changes:)

**Review by jonaslagoni — APPROVED** [review]
👍 

/rtm

**Comment by jonaslagoni** [comment]
@all-contributors please add @sambhavgupta0705 for docs

**Pull request merged**
