### PR TITLE
fix: set default to None for pydantic generator

### LINKED ISSUE #1644: PythonGenerator with Pydantic  If a property is Optional not required the json expected a key None
#### Describe the bug
PythonGenerator with Pydantic

#### How to Reproduce
If a property is Optional not required the json expected a key None

it is possible change the Class Python pydantic generator and add a default value =None for not required properties
from:
optionalkey: Optional[str] = Field( )
to:
optionalkey: Optional[str] = Field( default= None )

### PR DESCRIPTION
**Pull request by Harshil-Jani**
In pydantic based python generator, when the optional values are passed, they need to be passed with an `default=None` argument in Field().

image

**Related issue(s)**
 Fixes #1644

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Got some build and test problems, should be an easy fix. Let me know if you need anything 😄

**Comment by Harshil-Jani** [comment]
> Got some build and test problems, should be an easy fix. Let me know if you need anything 😄

Oh I see, I was not aware about the tests. Just updated the snapshots to work and added in same commit. Thanks for helping.

**Comment by jonaslagoni** [comment]
@Harshil-Jani remember to do the same for the examples ✌️

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Still need to update the examples `npm run test:examples:update` 🙂

**Comment by Harshil-Jani** [comment]
@jonaslagoni On it. Sorry for the delay. Will be fixing it right in next few hours.

**Review by jonaslagoni — APPROVED** [review]
Nice 💪

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Now a few linting problems 😄

**Comment by Harshil-Jani** [comment]
> Now a few linting problems 😄

@jonaslagoni Is there a way I can test the run locally on my system for linting, examples, tests all using a single command ? This way, It would be a lot easier for you to maintain 😢. And also this would reduce the actions ran on the CI. Or if it is not possible with just one command then maybe having it on the PR checklist would ensure that new contributors actually run things locally and pass tests or linting errors.

**Comment by jonaslagoni** [comment]
We actually dont 🤔
Great idea @Harshil-Jani! Would you like to add it in another PR?

**Comment by Harshil-Jani** [comment]
> We actually dont 🤔 Great idea @Harshil-Jani! Would you like to add it in another PR?

Sure. I will fix the linting errors and add the Checklist in yaml file for PRs.

**Review by jonaslagoni — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@all-contributors please add @Harshil-Jani for code and test

**Pull request merged**
