### PR TITLE
chore: add devilkiller-ag as codeowner

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
With his latest work on the playground: https://github.com/asyncapi/modelina/pull/1628 

I am suggesting we add @devilkiller-ag as a codeowner for the website 💪 

cc @kennethaasan @magicmatatjahu @Ferror @leigh-johnson @Samridhi-98 any objections? 

Lazy consensus will be used with @devilkiller-ag acceptance after 1 week from this PR creation 🙂

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@devilkiller-ag please approve the PR (or decline ;)) if you want to become a codeowner and take on that responsibility 🙂

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, I accept to be the code owner of the Modelina Website. However, I am not getting an option for approving this PR.

**Comment by jonaslagoni** [comment]
@devilkiller-ag if you go into `files changed` you should see a review button 🙂

**Review by devilkiller-ag — APPROVED** [review]

**Comment by devilkiller-ag** [comment]
Oh got it 😁. I thought I had to Approve the PR Merge.

**Review by Samridhi-98 — APPROVED** [review]

**Review by leigh-johnson — APPROVED** [review]
👋 Welcome @devilkiller-ag

**Comment by jonaslagoni** [comment]
Welcome again @devilkiller-ag 🎉

**Comment by devilkiller-ag** [comment]
> Welcome again @devilkiller-ag 🎉 

Thanks @jonaslagoni 😊

**Comment by jonaslagoni** [comment]
@devilkiller-ag you can now add yourself to the AsyncAPI TSC incase you are interested ✌️ 

Follow the same approach as here: https://github.com/asyncapi/community/pull/971

**Comment by devilkiller-ag** [comment]
> @devilkiller-ag you can now add yourself to the AsyncAPI TSC incase you are interested ✌️ 
> 
> Follow the same approach as here: https://github.com/asyncapi/community/pull/971

Sure, I will do this today✨

**Comment by kennethaasan** [comment]
Welcome!

**Comment by devilkiller-ag** [comment]
> Welcome!

Thanks @kennethaasan ✨

**Comment by derberg** [comment]
@jonaslagoni kind reminder that you need to invite @devilkiller-ag as maintainer to this repo, otherwise GitHub will not respect his approvals

**Comment by jonaslagoni** [comment]
🤦 Completely forgot thanks @derberg, @devilkiller-ag check your email, should have received the invite 🙂

**Comment by devilkiller-ag** [comment]
Thanks @jonaslagoni, I accepted the invite.

**Pull request merged**
