### PR TITLE
test: add python constraint tests

### LINKED ISSUE #1669: Add Python constraint tests
#### Reason/Context
Right now the Python constraints are not getting tested explicitly when they should. 

TODO:
- Create a new test file for each constraint logic in: https://github.com/asyncapi/modelina/tree/master/src/generators/python/constrainer

You can read more about constraints here: https://modelina.org/docs/constraints

Use the following TypeScript constraints as a guideline: https://github.com/asyncapi/modelina/tree/master/test/generators/typescript/constrainer

### PR DESCRIPTION
**Pull request by devilkiller-ag**
## Description
Added test for python tests

## Related Issue
Fixes #1669

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
@jonaslagoni I found some minor bugs in print statements of javascript constraint tests regarding name formatting. Should I fix that in this PR or open a Good First Issue?

**Comment by jonaslagoni** [comment]
For small things, feel free to bundle a few things, but general guideline is to split up PRs 🙂

**Comment by devilkiller-ag** [comment]
It's just a minor mistake in a sentence, I will rectify it. Do we have a problem with sonarcloud code duplication warning?

**Comment by jonaslagoni** [comment]
@devilkiller-ag no, you can ignore it 🙂

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
The tests are failing, double check the implementation to make sure the tests matches 🙂

**Comment by jonaslagoni** [comment]
@devilkiller-ag any update here? 🙂

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, I faced some test errors earlier, I will solve them and complete this PR by tomorrow!

**Comment by devilkiller-ag** [comment]
@jonaslagoni Do we need to pass this sonar cloud condition for duplication?

**Comment by jonaslagoni** [comment]
Nope, not at all 👍

**Review by jonaslagoni — APPROVED** [review]
Looks good to me 👌

**Comment by jonaslagoni** [comment]
@all-contributors please add @devilkiller-ag for docs, maintenance, test, code, design, review

**Pull request merged**
